### ISSUE TITLE
Link SLUB room navigator from the website

### ISSUE THREAD

**Issue by sebastianriese** [fsfw-dresden/homepage#20]

**Comment by jklmnn** [comment]
Hmm, ich hab mal geguckt, soweit ich das gesehen hab ist der SLUB-Navigator eine JS-App sodass kein Link zu einem speziellen Raum verfügbar ist. Außerdem scheint es nur bis Ebene 0 zu gehen, sodass der Raum nicht aufgeführt ist.
http://3d.slub-dresden.de/viewer?project_id=3&language=de&show_floor=11

**Comment by s72785** [comment]
zum teilen muss die (int)location zuvor ermittelt werden, dann kann man direkt verlinken:
?activate_location=
ABER der nicht einmal sauber eingezeichnete Arbeitsraum hat scheinbar keine Nummer, sondern nur die (Toiletten und) [Regale](http://3d.slub-dresden.de/viewer?activate_location=3991) drumherum  - dürfte zwar ausreichend genau sein, aber leider etwas irreführend.
Ich melde das mal als bug an die SLUB. done: [Ticket#2015043010000354] mal sehen wie lange es dauert.

**Comment by jklmnn** [comment]
Wie war das bei dir mit der Ebene? Ich hatte nur Zugriff auf die Ebenen 0, 1 und 2.

**Comment by s72785** [comment]
pfeil nachunten drücken gibt mir die sublevel .. no problem

**Comment by vv01f** [comment]
to be closed...

[...]
vielen Dank für Ihren Hinweis zur besseren Navigation auf unserer SLUB-Webseite, speziell den Raum -2.115 betreffend.
Gern bin ich Ihrer Bitte nachgekommen und habe den genannten Raum in unserer [Übersicht der Gruppenarbeitsräume](http://www.slub-dresden.de/service/arbeitsplaetze-arbeitsraeume/gruppenarbeitsraeume/) direkt mit den 3D-Modell verlinkt.
Weiteren Verlinkungen aller Räume werden schnellstmöglich folgen.

Möchten Sie den Link teilen, finden Sie ihn hier:
    http://3d.slub-dresden.de/viewer?project_id=3&amp;language=de&amp;activate_location=3022

Gern können Sie aber auch die Funktion direkt aus dem 3D-Modellbenutzen s. Abb. [Bild war in Email enthalten].
[...]
Wer den direkten Kontakt für weitere Hinweise haben mag, schreibe mit direkt.

**Comment by jklmnn** [comment]
Gelöst mit caafcf03918c1e8949fe556bc53e1b2d4852d616
