### ISSUE TITLE
Aktueller Commit 

### ISSUE THREAD

**Issue by jklmnn** [fsfw-dresden/homepage#4]
Soll die Seite von c8df5947fafc0bd2b4f1eb8e93aa964017ff1186 so übernommen werden?

**Comment by horazont** [comment]
Two follow-up questions before we put this live:
- Is the font free?
- Do we want to show focus on TU Dresden on the front page?

**Comment by sebastianriese** [comment]
Bin ich definitiv dafür. Damit sind auch #2 und #3 (erstmal) erledigt.

**Comment by arBmind** [comment]
Ich hab das Markup und den Text angepasst.

Selbst wenn der Font frei ist, sollten wir darauf zumindest hinweisen.

**Comment by vv01f** [comment]
s.a. pull-req 11 - hinweis auf font-lizens in README.md innerhalb des verz. für fonts

**Comment by vv01f** [comment]
die ursprungsfrage ist doch schon erledigt weil geschehen... ggf. jetzt nochmal die änderungen diskutieren und dann neu publishen.

**Comment by jklmnn** [comment]
Da der Master automatisch gepullt wird, ist die Seite jetzt so drin.
